// <auto-generated />
using System;
using Concierge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concierge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConciergeDbContext))]
    partial class ConciergeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("concierge")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concierge.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_session_id");

                    b.Property<Guid>("GuestVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_visit_id");

                    b.Property<DateTimeOffset?>("LastGuestMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_guest_message_at");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTimeOffset?>("LastStaffMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_staff_message_at");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("UnreadForStaff")
                        .HasColumnType("integer")
                        .HasColumnName("unread_for_staff");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("GuestVisitId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_visit");

                    b.HasIndex("ResortId", "RoomId", "LastMessageAt")
                        .HasDatabaseName("ix_conversation_resort_room_last");

                    b.ToTable("conversation", "concierge");
                });

            modelBuilder.Entity("Concierge.Domain.InternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_internal_note");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_internal_note_conversation_id");

                    b.HasIndex("ResortId", "RoomId")
                        .HasDatabaseName("ix_note_resort_room");

                    b.ToTable("internal_note", "concierge");
                });

            modelBuilder.Entity("Concierge.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReadByGuestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_by_guest_at");

                    b.Property<DateTimeOffset?>("ReadByStaffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_by_staff_at");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sender_type");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_message");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_message_conversation");

                    b.ToTable("message", "concierge");
                });

            modelBuilder.Entity("Concierge.Domain.InternalNote", b =>
                {
                    b.HasOne("Concierge.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_internal_note_conversation_conversation_id");
                });

            modelBuilder.Entity("Concierge.Domain.Message", b =>
                {
                    b.HasOne("Concierge.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_conversation_conversation_id");
                });
#pragma warning restore 612, 618
        }
    }
}
