// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResortQr.Infrastructure.Persistence;

#nullable disable

namespace ResortQr.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResortQr.Application.Identity.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_family");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_user");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.GuestAccess.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SessionKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_key_hash");

                    b.HasKey("Id")
                        .HasName("pk_guest_session");

                    b.HasIndex("SessionKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guestsession_key");

                    b.ToTable("guest_session", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.GuestAccess.GuestVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_session_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_guest_visit");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_visit_sweep")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("ResortId")
                        .HasDatabaseName("ix_guest_visit_resort_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_guest_visit_room_id");

                    b.HasIndex("GuestSessionId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("guest_visit", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_appuser_email");

                    b.HasIndex("ResortId")
                        .HasDatabaseName("ix_app_user_resort_id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.Resorts.Resort", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_resort");

                    b.ToTable("resort", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.Resorts.ResortLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_resort_language");

                    b.HasIndex("ResortId")
                        .IsUnique()
                        .HasDatabaseName("ux_lang_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("ResortId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_lang_code");

                    b.ToTable("resort_language", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.Resorts.ResortSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ChatEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("chat_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("FaqEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("faq_enabled");

                    b.Property<string>("GuestWebBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("guest_web_base_url");

                    b.Property<bool>("HousekeepingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("housekeeping_enabled");

                    b.Property<int>("HousekeepingRateLimitPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("housekeeping_rate_limit_per_hour");

                    b.Property<int>("MaxMessageLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_message_length");

                    b.Property<int>("MessageRateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("message_rate_limit_per_minute");

                    b.Property<int>("PortalWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("portal_window_minutes");

                    b.Property<bool>("RequireRuleAckForChat")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_chat");

                    b.Property<bool>("RequireRuleAckForFaq")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_faq");

                    b.Property<bool>("RequireRuleAckForHousekeeping")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_housekeeping");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("VisitIdleExpiryHours")
                        .HasColumnType("integer")
                        .HasColumnName("visit_idle_expiry_hours");

                    b.HasKey("Id")
                        .HasName("pk_resort_settings");

                    b.HasIndex("ResortId")
                        .IsUnique()
                        .HasDatabaseName("ux_resort_settings_resort");

                    b.ToTable("resort_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_idle_expiry", "visit_idle_expiry_hours > 0");

                            t.HasCheckConstraint("ck_msg_len", "max_message_length > 0");

                            t.HasCheckConstraint("ck_portal_window", "portal_window_minutes > 0");
                        });
                });

            modelBuilder.Entity("ResortQr.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("building");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("room_number");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("ResortId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_room_number")
                        .HasFilter("is_deleted = false");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.Rooms.RoomQrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<string>("TokenPreview")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("token_preview");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_room_qr_token");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasDatabaseName("ux_qr_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_qrtoken_token");

                    b.ToTable("room_qr_token", (string)null);
                });

            modelBuilder.Entity("ResortQr.Domain.GuestAccess.GuestVisit", b =>
                {
                    b.HasOne("ResortQr.Domain.GuestAccess.GuestSession", null)
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_visit_guest_session_guest_session_id");

                    b.HasOne("ResortQr.Domain.Resorts.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_visit_resorts_resort_id");

                    b.HasOne("ResortQr.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_visit_rooms_room_id");
                });

            modelBuilder.Entity("ResortQr.Domain.Identity.AppUser", b =>
                {
                    b.HasOne("ResortQr.Domain.Resorts.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_resorts_resort_id");
                });

            modelBuilder.Entity("ResortQr.Domain.Resorts.ResortLanguage", b =>
                {
                    b.HasOne("ResortQr.Domain.Resorts.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resort_language_resort_resort_id");
                });

            modelBuilder.Entity("ResortQr.Domain.Resorts.ResortSettings", b =>
                {
                    b.HasOne("ResortQr.Domain.Resorts.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resort_settings_resort_resort_id");
                });

            modelBuilder.Entity("ResortQr.Domain.Rooms.Room", b =>
                {
                    b.HasOne("ResortQr.Domain.Resorts.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_resort_resort_id");
                });

            modelBuilder.Entity("ResortQr.Domain.Rooms.RoomQrToken", b =>
                {
                    b.HasOne("ResortQr.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_qr_token_room_room_id");
                });
#pragma warning restore 612, 618
        }
    }
}
