// <auto-generated />
using System;
using Faq.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Faq.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FaqDbContext))]
    [Migration("20260715192548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("faq")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Faq.Domain.FaqCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_faq_category");

                    b.HasIndex("ResortId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_faq_category_key");

                    b.HasIndex("ResortId", "SortOrder")
                        .HasDatabaseName("ix_faq_category_resort_order");

                    b.ToTable("faq_category", "faq");
                });

            modelBuilder.Entity("Faq.Domain.FaqCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FaqCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("faq_category_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_faq_category_translation");

                    b.HasIndex("FaqCategoryId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_faq_category_translation_lang");

                    b.ToTable("faq_category_translation", "faq");
                });

            modelBuilder.Entity("Faq.Domain.FaqItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_faq_item");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_faq_item_parent");

                    b.HasIndex("CategoryId", "SortOrder")
                        .HasDatabaseName("ix_faq_item_category_order");

                    b.ToTable("faq_item", "faq");
                });

            modelBuilder.Entity("Faq.Domain.FaqItemTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerHtmlSanitized")
                        .HasColumnType("text")
                        .HasColumnName("answer_html_sanitized");

                    b.Property<Guid>("FaqItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("faq_item_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_code");

                    b.Property<string>("Question")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_faq_item_translation");

                    b.HasIndex("FaqItemId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_faq_item_translation_lang");

                    b.ToTable("faq_item_translation", "faq");
                });

            modelBuilder.Entity("Faq.Domain.FaqCategoryTranslation", b =>
                {
                    b.HasOne("Faq.Domain.FaqCategory", null)
                        .WithMany()
                        .HasForeignKey("FaqCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_faq_category_translation_faq_category_faq_category_id");
                });

            modelBuilder.Entity("Faq.Domain.FaqItem", b =>
                {
                    b.HasOne("Faq.Domain.FaqCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_faq_item_faq_category_category_id");

                    b.HasOne("Faq.Domain.FaqItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_faq_item_faq_item_parent_id");
                });

            modelBuilder.Entity("Faq.Domain.FaqItemTranslation", b =>
                {
                    b.HasOne("Faq.Domain.FaqItem", null)
                        .WithMany()
                        .HasForeignKey("FaqItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_faq_item_translation_faq_item_faq_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
