// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rules.Infrastructure.Persistence;

#nullable disable

namespace Rules.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RulesDbContext))]
    [Migration("20260715014025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rules")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rules.Domain.RuleAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid>("GuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_session_id");

                    b.Property<Guid>("GuestVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_visit_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("RulePublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_publication_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rule_acknowledgement");

                    b.HasIndex("RulePublicationId")
                        .HasDatabaseName("ix_rule_acknowledgement_rule_publication_id");

                    b.HasIndex("GuestVisitId", "RulePublicationId")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_ack_visit_publication");

                    b.ToTable("rule_acknowledgement", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RulePublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("change_note");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rule_publication");

                    b.HasIndex("ResortId")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_publication_current")
                        .HasFilter("is_current");

                    b.HasIndex("ResortId", "Version")
                        .HasDatabaseName("ix_rule_publication_resort_version");

                    b.ToTable("rule_publication", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RulePublicationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<int>("MinReadSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("min_read_seconds");

                    b.Property<bool>("RequireScrollEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("require_scroll_end");

                    b.Property<Guid>("RulePublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_publication_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_rule_publication_section");

                    b.HasIndex("RulePublicationId", "SortOrder")
                        .HasDatabaseName("ix_rule_publication_section_order");

                    b.ToTable("rule_publication_section", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RulePublicationSectionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtmlSanitized")
                        .HasColumnType("text")
                        .HasColumnName("body_html_sanitized");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("RulePublicationSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_publication_section_id");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_rule_publication_section_translation");

                    b.HasIndex("RulePublicationSectionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_pub_section_translation_lang");

                    b.ToTable("rule_publication_section_translation", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RuleSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<int>("MinReadSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("min_read_seconds");

                    b.Property<bool>("RequireScrollEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("require_scroll_end");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_set_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_rule_section");

                    b.HasIndex("RuleSetId", "SortOrder")
                        .HasDatabaseName("ix_rule_section_set_order");

                    b.ToTable("rule_section", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RuleSectionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtmlSanitized")
                        .HasColumnType("text")
                        .HasColumnName("body_html_sanitized");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_code");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("RuleSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_section_id");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_rule_section_translation");

                    b.HasIndex("RuleSectionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_section_translation_lang");

                    b.ToTable("rule_section_translation", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rule_set");

                    b.HasIndex("ResortId")
                        .HasDatabaseName("ix_rule_set_resort");

                    b.ToTable("rule_set", "rules");
                });

            modelBuilder.Entity("Rules.Domain.RuleAcknowledgement", b =>
                {
                    b.HasOne("Rules.Domain.RulePublication", null)
                        .WithMany()
                        .HasForeignKey("RulePublicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rule_acknowledgement_rule_publications_rule_publication_id");
                });

            modelBuilder.Entity("Rules.Domain.RulePublicationSection", b =>
                {
                    b.HasOne("Rules.Domain.RulePublication", null)
                        .WithMany()
                        .HasForeignKey("RulePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_publication_section_rule_publication_rule_publication_");
                });

            modelBuilder.Entity("Rules.Domain.RulePublicationSectionTranslation", b =>
                {
                    b.HasOne("Rules.Domain.RulePublicationSection", null)
                        .WithMany()
                        .HasForeignKey("RulePublicationSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_publication_section_translation_rule_publication_secti");
                });

            modelBuilder.Entity("Rules.Domain.RuleSection", b =>
                {
                    b.HasOne("Rules.Domain.RuleSet", null)
                        .WithMany()
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_section_rule_sets_rule_set_id");
                });

            modelBuilder.Entity("Rules.Domain.RuleSectionTranslation", b =>
                {
                    b.HasOne("Rules.Domain.RuleSection", null)
                        .WithMany()
                        .HasForeignKey("RuleSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_section_translation_rule_section_rule_section_id");
                });
#pragma warning restore 612, 618
        }
    }
}
