<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModuleName.Application\ModuleName.Application.csproj" />
    <ProjectReference Include="..\..\..\Bedrock.Api\Bedrock.Api.csproj" />
  </ItemGroup>
</Project>
