// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResortConfig.Infrastructure.Persistence;

#nullable disable

namespace ResortConfig.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResortConfigDbContext))]
    partial class ResortConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("resort_config")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResortConfig.Domain.Resort", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_resort");

                    b.ToTable("resort", "resort_config");
                });

            modelBuilder.Entity("ResortConfig.Domain.ResortLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_resort_language");

                    b.HasIndex("ResortId")
                        .IsUnique()
                        .HasDatabaseName("ux_lang_default")
                        .HasFilter("is_default");

                    b.HasIndex("ResortId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_lang_code");

                    b.ToTable("resort_language", "resort_config");
                });

            modelBuilder.Entity("ResortConfig.Domain.ResortSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ChatEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("chat_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("FaqEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("faq_enabled");

                    b.Property<string>("GuestWebBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("guest_web_base_url");

                    b.Property<bool>("HousekeepingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("housekeeping_enabled");

                    b.Property<int>("HousekeepingRateLimitPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("housekeeping_rate_limit_per_hour");

                    b.Property<int>("MaxMessageLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_message_length");

                    b.Property<int>("MessageRateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("message_rate_limit_per_minute");

                    b.Property<int>("PortalWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("portal_window_minutes");

                    b.Property<bool>("RequireRuleAckForChat")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_chat");

                    b.Property<bool>("RequireRuleAckForFaq")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_faq");

                    b.Property<bool>("RequireRuleAckForHousekeeping")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rule_ack_for_housekeeping");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("VisitIdleExpiryHours")
                        .HasColumnType("integer")
                        .HasColumnName("visit_idle_expiry_hours");

                    b.HasKey("Id")
                        .HasName("pk_resort_settings");

                    b.HasIndex("ResortId")
                        .IsUnique()
                        .HasDatabaseName("ux_resort_settings_resort");

                    b.ToTable("resort_settings", "resort_config", t =>
                        {
                            t.HasCheckConstraint("ck_idle_expiry", "visit_idle_expiry_hours > 0");

                            t.HasCheckConstraint("ck_msg_len", "max_message_length > 0");

                            t.HasCheckConstraint("ck_portal_window", "portal_window_minutes > 0");
                        });
                });

            modelBuilder.Entity("ResortConfig.Domain.ResortLanguage", b =>
                {
                    b.HasOne("ResortConfig.Domain.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resort_language_resort_resort_id");
                });

            modelBuilder.Entity("ResortConfig.Domain.ResortSettings", b =>
                {
                    b.HasOne("ResortConfig.Domain.Resort", null)
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resort_settings_resort_resort_id");
                });
#pragma warning restore 612, 618
        }
    }
}
