<Project Sdk="Microsoft.NET.Sdk">
  <!-- Application → Domain, SharedKernel. KHÔNG Api/Infrastructure. -->
  <ItemGroup>
    <ProjectReference Include="..\Foundation.Domain\Foundation.Domain.csproj" />
    <ProjectReference Include="..\Foundation.SharedKernel\Foundation.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
