// <auto-generated />
using System;
using GuestAccess.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuestAccess.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuestAccessDbContext))]
    partial class GuestAccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("guest_access")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestAccess.Domain.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SessionKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_key_hash");

                    b.HasKey("Id")
                        .HasName("pk_guest_session");

                    b.HasIndex("SessionKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_session_key_hash");

                    b.ToTable("guest_session", "guest_access");
                });

            modelBuilder.Entity("GuestAccess.Domain.GuestVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_session_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_guest_visit");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_visit_active_expiry")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("GuestSessionId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_visit_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("guest_visit", "guest_access", t =>
                        {
                            t.HasCheckConstraint("ck_guest_visit_closed_at", "(status = 'Active' AND closed_at IS NULL) OR (status IN ('Closed', 'Expired') AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_guest_visit_expiry_after_seen", "expires_at >= last_seen_at");
                        });
                });

            modelBuilder.Entity("GuestAccess.Domain.GuestVisit", b =>
                {
                    b.HasOne("GuestAccess.Domain.GuestSession", null)
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_visit_guest_session_guest_session_id");
                });
#pragma warning restore 612, 618
        }
    }
}
