// <auto-generated />
using System;
using Housekeeping.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Housekeeping.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HousekeepingDbContext))]
    [Migration("20260728050107_AddOutboxReplayAudit")]
    partial class AddOutboxReplayAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("housekeeping")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Housekeeping.Domain.HousekeepingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HousekeepingTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("housekeeping_ticket_id");

                    b.Property<string>("Method")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("new_status");

                    b.HasKey("Id")
                        .HasName("pk_housekeeping_event");

                    b.HasIndex("HousekeepingTicketId", "CreatedAt")
                        .HasDatabaseName("ix_hk_event_ticket");

                    b.ToTable("housekeeping_event", "housekeeping");
                });

            modelBuilder.Entity("Housekeeping.Domain.HousekeepingTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmenitySoap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("amenity_soap");

                    b.Property<int>("AmenityToothbrush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("amenity_toothbrush");

                    b.Property<int>("AmenityTowel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("amenity_towel");

                    b.Property<int>("AmenityWater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("amenity_water");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<string>("CompletionMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("completion_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GuestVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_visit_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PreferredTime")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_time");

                    b.Property<string>("PreferredTimeText")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("preferred_time_text");

                    b.Property<Guid?>("RequestedByGuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_guest_session_id");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid")
                        .HasColumnName("resort_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_housekeeping_ticket");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasDatabaseName("ux_hk_open_ticket_room")
                        .HasFilter("status IN ('Requested','InProgress')");

                    b.HasIndex("ResortId", "Status")
                        .HasDatabaseName("ix_hk_ticket_resort_status");

                    b.ToTable("housekeeping_ticket", "housekeeping");
                });

            modelBuilder.Entity("Housekeeping.Domain.HousekeepingEvent", b =>
                {
                    b.HasOne("Housekeeping.Domain.HousekeepingTicket", null)
                        .WithMany()
                        .HasForeignKey("HousekeepingTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_housekeeping_event_housekeeping_tickets_housekeeping_ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
